services:

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - redis-net

  mongo:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27099:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/easylogs --quiet
      interval: 10s
      timeout: 10s
      retries: 3

  easylogs:
    build:
      context: .
    restart: always
    environment:
      MONGO_DB: ${MONGO_DB:-easylogs}
      MONGO_URI: ${MONGO_URI:-mongodb://root:example@mongo:27017}
      REDIS_URI: ${REDIS_URI:-redis://redis:6379}
      RECEIVE_LOGS_KEY: ${RECEIVE_LOGS_KEY:-LIh982y87GgljahsadfklJHLIUG87g1u1e7f6eb2ee145571858e8e24}
      ADMIN_USER: ${ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-adminadmin}
    ports:
      - '8080:8080'
    networks:
      - mongo-net
      - redis-net
    depends_on:
      - mongo

volumes:
  mongo-data:
  redis-data:

networks:
  mongo-net:
  redis-net:
